name: Post Market Auto
on:
  schedule:
    - cron: '5 1 * * 1-5'   # 09:05 TPE
    - cron: '35 5 * * 1-5'  # 15:30 TPE
    - cron: '30 12 * * 1-5' # 20:30 TPE
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Taipei
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Write service account json
        run: echo "$GOOGLE_CREDENTIALS" > service_account.json
      - run: python post_market.py
