name: Post Market Auto
on:
  schedule:
    - cron: '5 1 * * 1-5'
    - cron: '30 12 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ← 在這裡插入步驟
      - name: Write service account json
        shell: bash
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          printf "%s" "$GOOGLE_CREDENTIALS" > service_account.json
          ls -l service_account.json
          head -c 80 service_account.json || true

      - run: python post_market.py
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
