# /.github/workflows/post_market.yml
name: Run post_market.py

on:
  schedule:
    - cron: '5 0 * * *'     # 台灣時間 09:05
    - cron: '0 7 * * *'     # 台灣時間 15:00
    - cron: '30 12 * * *'   # 台灣時間 20:30
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run post_market.py
        run: python post_market.py
